POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "josdhn@dqqqoe.com",
  "password": "aA1!11111"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json


{
  "users": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "email": "john@doesdsdsd.com",
      "password": "aA1!11111"
    },
    {
      "firstName": "Jane",
      "lastName": "Doe",
      "email": "jane@doesdfsdf.com",
      "password": "aA1!11111"
    }
  ]
}
