POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "josdhn@dqqqoe.com",
  "password": "aA1!11111"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9zZGhuQGRxcXFvZS5jb20iLCJpYXQiOjE3NTcxNjU4MjcsImV4cCI6MTc1NzE2OTQyNywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.ouT0V93hqP4bf3988DF3_yvMpFjuKAfr2GK7uH0DXQg


{
  "users": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "email": "john@doesdsdsd1.com",
      "password": "aA1!11111"
    },
    {
      "firstName": "Jane",
      "lastName": "Doe",
      "email": "jane@doesdfsdf2.com",
      "password": "aA1!11111"
    }
  ]
}
